defaults: &defaults
  docker:
    - image: node:8-wheezy
  working_directory: /usr/src/app

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Update npm
          command: npm install -g npm @latest
      - restore_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}
      - run:
          name: Install node modules
          command: npm ci
      - save_cache:
          key: npm-v1-{{ checksum "package-lock.json" }}
          paths:
            - /usr/src/app/node_modules
      - persist_to_workspace:
          root: /usr/src
          paths:
            - app
      - run:
          name: Run tests
          command: npm test
      - store_artifacts:
          path: /usr/src/app/coverage
